#!name=荔枝音频解锁 (GitHub)
#!desc=解锁荔枝App付费内容试听限制。
#!author=baby
#!icon=https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/3d/8c/9b/3d8c9b31-827c-0112-789a-01582737603c/AppIcon-0-0-1x_U007etouch-0-0-85-220.png/180x180bb.png

[Script]
# 匹配荔枝接口并调用远程脚本
荔枝音频 = type=http-response, pattern=^https?:\/\/httpproxy101\.lizhifm\.com\/op\/, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js

[MITM]
# 精准添加域名，防止全App断网
hostname = %APPEND% httpproxy101.lizhifm.com
