[Script]
# 改为 request 类型，只打印 URL，不解密返回体
荔枝测试 = type=http-request, pattern=^https?:\/\/httpproxy101\.lizhifm\.com\/op\/, script-path=https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js

[MITM]
hostname = httpproxy101.lizhifm.com
