#!name=荔枝音频解锁
#!desc=解锁荔枝App付费内容试听限制
#!author=baby
#!icon=https://is1-ssl.mzstatic.com/image/thumb/Purple122/v4/3d/8c/9b/3d8c9b31-827c-0112-789a-01582737603c/AppIcon-0-0-1x_U007etouch-0-0-85-220.png/180x180bb.png

[Script]
# 注意：等号两边不要留空格，URL匹配正则要精准
荔枝音频 = type=http-response, pattern=^https?:\/\/httpproxy101\.lizhifm\.com\/op\/, requires-body=1, max-size=0, script-path=https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js

[MITM]
hostname = %APPEND% httpproxy101.lizhifm.com
