// ==UserScript==
// @ScriptName        荔枝音频解锁
// @Author            baby
// @Function          解锁荔枝App付费内容试听限制，尝试绕过播放鉴权
// @UpdateTime        2026-04-21
// @Attention         自用脚本，仅供交流学习
// @Version           V1.0.0
// @ScriptURL         https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi2.conf
// ==/UserScript==

# > 荔枝音频鉴权解锁 (精准匹配 op 接口)
# > 对应 JS 地址请确保为你的 GitHub Raw 链接
# ^https?:\/\/httpproxy101\.lizhifm\.com\/op\/ url script-response-body https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js
# > 荔枝音频鉴权解锁 - 专项处理 5763 报警接口
^https?:\/\/.*\.lizhifm\.com\/op\/5763 url script-response-body https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js


[MITM]
hostname = httpproxy101.lizhifm.com
