// ==UserScript==
// @ScriptName        荔枝音频解锁
// @Author            baby
// @Function          解锁荔枝App付费内容试听限制，尝试绕过播放鉴权
// @UpdateTime        2026-04-21
// @Attention         自用脚本，仅供交流学习
// @Version           V1.0.0
// @ScriptURL         https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi2.conf
// ==/UserScript==


# > 账户余额伪装
^https?:\/\/livepay\.lz310\.com\/payweb\/recharge\/queryAccessBalanceV2 url script-response-body https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js

[MITM]
hostname = *.lizhifm.com, livepay.lz310.com

