[rewrite_local]
# 改用脚本，脚本才能识别 \d+ (正则表达式)
^https?:\/\/.*\.lizhifm\.com\/op\/5641 url script-response-body https://raw.githubusercontent.com/bxy0128/my_bed/master/lizhi.js

[MITM]
hostname = *.lizhifm.com
